admins: []
forwards:
- source: -1001230197447
  dest:
  - -1001614264545
  offset: 5990
  end: 6000
show_forwarded_from: false
live:
  delete_sync: false
  delete_on_edit: null
past:
  delay: 3.0
plugins:
  replace:
    text:
      '@Telugudubbing_movies - ': 'Join @MVS_REQ - '
      'ğŸ§¡ First On Telegram ğŸ§¡ â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â­• @Tamil_Serieszâ­• @Tv_Web_Serieszâ­• @Tamil_Old_Flimsâ­• @Tamil_DUB_Moviesâ­• @Sons_of_TamilRockersâ­• @Tamil_HD_Movies_Requestsâ  Group : ğŸ¯â­• @Discussion_HD_Movies ğŸ’¬â  Click Here More Channelsâ­• @Tamil_LinkzZ (All in One)' : 'Join @REQ_MVS'
    regex: true
